public without sharing class AccessApplicationFetcher {

	public static List<PermissionSetAssignment> getCurrentlyAssignedPermsets() {
		return null;
	}

	public static List<PermissionSet> getAllPermissionSetsAvailable() {

		//todo only fetch for correct license
		return null;
	}

	public static List<PermissionSetGroup> getAllPermissionSetGroupsAvailable() {

		return null;
	}

	public static List<AccessApplication__c> getAccessApplications( ) {
		return null;
	}
}
